<?php

/**
 * Class ProviderTest
 * @group provider
 */
class ProviderTest extends TestCase
{

    private $app;

    public function setUp()
    {
        $this->app = new \MyStuff\Application();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testVerificaObjetosIguaisTantoDoProviderQuandoInstanciado()
    {



        $config = new \MyStuff\Config\Config(__DIR__);

        $configApp = $this->app['config'];

        $this->assertInstanceOf(get_class($config), $configApp);

    }

    public function testRetorneValorDeCaminhoPublicUsandoProvider()
    {
        $configApp = $this->app['config'];

        $this->assertTrue(is_array($configApp->get('app')));
    }

}